# Generated by Django 3.0.5 on 2020-04-15 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('work_address', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('Vacation', 'Vacation'), ('One_Day', 'One Day Visit'), ('Overnight', 'Overnight'), ('Event', 'Event'), ('Pool_Gym', 'Use Pool/Gym')], max_length=50)),
                ('visitor_count', models.IntegerField()),
                ('visitor_names', models.TextField()),
                ('visit_date', models.DateField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Processing', 'Processing'), ('Done', 'Done')], default='Pending', max_length=50)),
                ('info_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('complain', models.CharField(choices=[('Maintenance', 'Maintenance Problem'), ('Staff', 'Staff Conflict'), ('Neighbour', 'Neighbor/s Issue'), ('Pest', 'Pest Invasion'), ('Property_Condition', 'Condition of Property'), ('Safety', 'Safety Concern'), ('Billing', 'Billing'), ('Others', 'Others')], max_length=50)),
                ('elaborate', models.TextField(blank=True)),
                ('neighbour', models.CharField(blank=True, max_length=50)),
                ('staff', models.CharField(blank=True, max_length=50)),
                ('supporting_image', models.CharField(blank=True, max_length=2048)),
                ('info_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('billing_type', models.CharField(choices=[('Association_Dues', 'Association Dues'), ('Water', 'Water'), ('Electric', 'Electric'), ('Cable', 'Cable'), ('Internet', 'Internet'), ('Rent', 'Rent')], max_length=20)),
                ('billing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Processing', 'Processing')], default='Pending', max_length=50)),
                ('info_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Tenant')),
            ],
        ),
    ]
